
---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:20 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@e-dis.de <ide-team@e-dis.de>
Gesendet: Montag, 30. November 2020 14:04
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: PUT Neues E-Mail Zertifikat für die E.DIS Netz GmbH (9901000000001) / MP: Leu Energie GmbH & Co. KG (9979004000004)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der E.DIS Netz GmbH (9901000000001), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für EDI-VNB-BIS-PROD@e-dis.de findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=EDI-VNB-BIS-PROD@e-dis.de

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840187&serial=662b92613cce590b635b92b11c97a47653244955&cn=EDI-VNB-BIS-PROD&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (Leu Energie GmbH & Co. KG; 9979004000004) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T 0800 – 222 45 00
ide-team@e-dis.de

E.DIS Netz GmbH
Langewahler Straße 60
15517 Fürstenwalde
www.e-dis-netz.de


Geschäftsführung: Stefan Blache,  Harald Bock,  Michael Kaiser
Sitz: Fürstenwalde/Spree,  Amtsgericht Frankfurt (Oder),  HRB 16068 FF




---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:32 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@energienetze-bayern.com <ide-team@energienetze-bayern.com>
Gesendet: Montag, 30. November 2020 15:01
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: PUU Neues E-Mail Zertifikat für die Energienetze Bayern GmbH (9907510000002) / MP: sonnen eServices GmbH (9978763000008)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der Energienetze Bayern GmbH (9907510000002), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für edifact-vnb@energienetze-bayern.com findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=edifact-vnb@energienetze-bayern.com

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840135&serial=77e4e0d9583e89f43df89888ab25b85d4aebbe00&cn=EBYE-VNB-EDIFACT&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (sonnen eServices GmbH; 9978763000008) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T 0800 – 224 40 99
IDE-Team@energienetze-bayern.com

Energienetze Bayern GmbH
Lilienthalstraße 7
93049 Regensburg
www.energienetze-bayern.com


Geschäftsführer: Roland Kurzbeck, Christoph Neumeier Sitz Regensburg Lilienthalstraße 7 93049 Regensburg,  Amtsgericht Regensburg, HRB  10367



---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:41 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@sh-netz.com <ide-team@sh-netz.com>
Gesendet: Montag, 30. November 2020 15:12
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: *SPAM* PUT Neues E-Mail Zertifikat für die Schleswig-Holstein Netz AG (9900535000007) / MP: sonnen eServices GmbH (9978763000008)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der Schleswig-Holstein Netz AG (9900535000007), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für SHNG-VNB-BIS-PROD@SH-Netz.com findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=SHNG-VNB-BIS-PROD@SH-Netz.com

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840377&serial=553d0c5e53c4e9de8b06851218b0e0ff26acead9&cn=SHNG-VNB-BIS-PROD&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (sonnen eServices GmbH; 9978763000008) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T +49 4106-648 900 20
ide-team@sh-netz.com

Schleswig-Holstein Netz AG
Schleswag-HeinGas-Platz 1
25450 Quickborn
www.sh-netz.com


Sitz: Quickborn,  Amtsgericht Pinneberg,  HRB 8122 PI Vorsitzender des Aufsichtsrats: Matthias Boxberger, Vorstand: Kirsten Fust,  Dr. Joachim Kabs,  Stefan Strobl



---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:20 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@e-dis.de <ide-team@e-dis.de>
Gesendet: Montag, 30. November 2020 14:04
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: PUT Neues E-Mail Zertifikat für die E.DIS Netz GmbH (9901000000001) / MP: Leu Energie GmbH & Co. KG (9979004000004)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der E.DIS Netz GmbH (9901000000001), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für EDI-VNB-BIS-PROD@e-dis.de findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=EDI-VNB-BIS-PROD@e-dis.de

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840187&serial=662b92613cce590b635b92b11c97a47653244955&cn=EDI-VNB-BIS-PROD&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (Leu Energie GmbH & Co. KG; 9979004000004) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T 0800 – 222 45 00
ide-team@e-dis.de

E.DIS Netz GmbH
Langewahler Straße 60
15517 Fürstenwalde
www.e-dis-netz.de


Geschäftsführung: Stefan Blache,  Harald Bock,  Michael Kaiser
Sitz: Fürstenwalde/Spree,  Amtsgericht Frankfurt (Oder),  HRB 16068 FF




---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:32 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@energienetze-bayern.com <ide-team@energienetze-bayern.com>
Gesendet: Montag, 30. November 2020 15:01
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: PUU Neues E-Mail Zertifikat für die Energienetze Bayern GmbH (9907510000002) / MP: sonnen eServices GmbH (9978763000008)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der Energienetze Bayern GmbH (9907510000002), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für edifact-vnb@energienetze-bayern.com findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=edifact-vnb@energienetze-bayern.com

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840135&serial=77e4e0d9583e89f43df89888ab25b85d4aebbe00&cn=EBYE-VNB-EDIFACT&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (sonnen eServices GmbH; 9978763000008) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T 0800 – 224 40 99
IDE-Team@energienetze-bayern.com

Energienetze Bayern GmbH
Lilienthalstraße 7
93049 Regensburg
www.energienetze-bayern.com


Geschäftsführer: Roland Kurzbeck, Christoph Neumeier Sitz Regensburg Lilienthalstraße 7 93049 Regensburg,  Amtsgericht Regensburg, HRB  10367



---------- Forwarded message ----------
From: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
To: "zerti_manager@ops.xpergy.com" <zerti_manager@ops.xpergy.com>
Cc: 
Bcc: 
Date: Wed, 2 Dec 2020 12:18:41 +0000
Subject: wg



Amtsgericht Essen HRB 25724     
Vorstand: Christian Hövelhaus (CEO), Christoph Gardlo (COO)     Aufsichtsratsvorsitzender: Dr. Klaus Kasper

Bitte beachten Sie unsere Datenschutzinformation. / Please note our privacy statement. www.esforin.com/datenschutz
-----Ursprüngliche Nachricht-----
Von: ide-team@sh-netz.com <ide-team@sh-netz.com>
Gesendet: Montag, 30. November 2020 15:12
An: mabis-clearing ES FOR IN SE <mabis-clearing@esforin.com>
Betreff: *SPAM* PUT Neues E-Mail Zertifikat für die Schleswig-Holstein Netz AG (9900535000007) / MP: sonnen eServices GmbH (9978763000008)

Sehr geehrte Damen und Herren,

in Kürze verliert unser derzeitiges Zertifikat vorzeitig und außerplanmäßig seine Gültigkeit, da der Betrieb der zugrundeliegenden CA zum 16.12.2020 eingestellt wird.
Hiermit erhalten Sie das neue Zertifikat für die 1:1 EDIFACT-Adresse der Schleswig-Holstein Netz AG (9900535000007), welches Sie ab sofort nutzen können.

ACHTUNG: Der Austausch ist zwingend notwendig, da das aktuell verwendete Zertifikat demnächst gesperrt wird (revoked).

Eine Übersicht der Zertifikate für SHNG-VNB-BIS-PROD@SH-Netz.com findet sich unter folgendem Link:
http://certificatelookup.quovadisglobal.com/default.aspx?email=SHNG-VNB-BIS-PROD@SH-Netz.com

Bitte benutzen Sie folgenden direkten Downloadlink für das neue Zertifikat:
http://certificatelookup.quovadisglobal.com/getFile.aspx?id=2840377&serial=553d0c5e53c4e9de8b06851218b0e0ff26acead9&cn=SHNG-VNB-BIS-PROD&type=cert

Unter folgenden Links stehen die zugehörigen Root-CA und Sub-CA zur Verfügung:
Root CA: http://trust.quovadisglobal.com/qvrca1g3.crt
Sub CA: http://trust.quovadisglobal.com/quovadiseuropeadvancedcag2.crt

Wir werden das neue Zertifikat ab dem 14.12.2020 um 12:00 Uhr für ausgehenden Nachrichten einsetzen.

Bitte setzen Sie (sonnen eServices GmbH; 9978763000008) die erforderlichen Maßnahmen in Ihrem System um.

Für Rückfragen stehen wir gern zur Verfügung. Vielen Dank.

Freundliche Grüße
Ihr IDE Team

Netznutzungsmanagement
Lieferantenwechsel/Marktkommunikation
T +49 4106-648 900 20
ide-team@sh-netz.com

Schleswig-Holstein Netz AG
Schleswag-HeinGas-Platz 1
25450 Quickborn
www.sh-netz.com